system:
  apiurl: "http://localhost:9090/api.php"
  addr: 8080
  env: public
  db-type: mysql
  oss-type: aws-s3
  use-multipoint: false
  use-redis: true
  iplimit-count: 15000
  iplimit-time: 3600
  router-prefix: ""

mysql:
  path: 127.0.0.1
  port: "3309"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: wikidb
  username: wikiuser
  password: 12345678
  prefix: ""
  singular: false
  engine: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: Info
  log-zap: true

redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""

captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  open-captcha: 0
  open-captcha-timeout: 3600

jwt:
  signing-key: 05fa1605-fa9d-41fb-ad56-7af9a656214a
  expires-time: 7d
  buffer-time: 1d
  issuer: qmPlus


db-list:
  - disable: true
    type: ""
    alias-name: ""
    path: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    prefix: ""
    singular: false
    engine: ""
    max-idle-conns: 10
    max-open-conns: 100
    log-mode: ""
    log-zap: false

email:
  to: xxx@qq.com
  port: 465
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test



zap:
  level: info
  prefix: 'wiki-game'
  format: Console
  director: log
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  max-age: 0
  show-line: true
  log-in-console: true

cors:
  mode: allow-all # 放行模式: allow-all, 放行全部; whitelist, 白名单模式, 来自白名单内域名的请求添加 cors 头; strict-whitelist 严格白名单模式, 白名单外的请求一律拒绝
  whitelist:
    - allow-origin: example1.com
      allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
      allow-methods: POST, GET
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type

      allow-credentials: true # 布尔值
    - allow-origin: example2.com
      allow-headers: content-type
      allow-methods: GET, POST
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
      allow-credentials: true # 布尔值